name: nalsflutter
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  app_links: 6.4.0
  # artemis: 7.12.0-beta.1
  async: 2.13.0
  auto_route: 10.1.0
  cached_network_image: 3.4.1
  chatview:
    git:
      url: https://github.com/minhnt3/flutter_chatview.git
      ref: main
  clock: 1.1.2
  cloud_firestore: 5.6.9
  connectivity_plus: 6.1.4
  dartx: 1.2.0
  decimal: 3.2.1
  device_info_plus: 11.4.0
  device_preview_plus: 2.4.2
  dio: 5.8.0+1
  # dio_cookie_manager: 3.1.0
  encrypted_shared_preferences: 3.0.1
  firebase_analytics: 11.5.0
  firebase_auth: 5.6.0
  firebase_core: 3.14.0
  firebase_crashlytics: 4.3.7
  firebase_messaging: 15.2.7
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.4.1
  flutter_hooks: 0.21.2
  flutter_linkify: 6.0.0
  flutter_local_notifications: 19.2.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: 2.4.6
  flutter_secure_storage: 9.2.4
  flutter_svg: 2.1.0
  flutter_udid: 4.0.0
  #   url_launcher: 6.3.1
  focus_detector_v2: 3.1.0+1
  freezed_annotation: 3.0.0
  # geolocator: 10.1.0
  # get_it: 7.6.0
  # gql: 0.14.0
  # gql_dio_link: 0.3.0
  # graphql_flutter: 5.1.2
  hooks_riverpod: 2.6.1
  infinite_scroll_pagination: 5.0.0
  injectable: 2.5.0
  intl: 0.20.2
  isar:
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: 3.1.8
    hosted: https://pub.isar-community.dev/
  json_annotation: 4.9.0
  mime: 2.0.0
  package_info_plus: 8.3.0
  path_provider: 2.1.5
  popup_menu: 2.1.0
  rxdart: 0.28.0
dev_dependencies:
  auto_route_generator: 10.2.3
  build_runner: 2.4.15
  custom_lint: 0.7.5
  # dart_code_metrics: 5.7.6
  flutter_driver:
    sdk: flutter
  flutter_gen_runner: 5.10.0
  flutter_launcher_icons: 0.14.4
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  freezed: 3.0.6
  golden_toolkit: 0.15.0
  injectable_generator: 2.7.0
  integration_test:
    sdk: flutter
  intl_utils: 2.8.10
  isar_generator:
    git:
      url: https://github.com/minhnt3/isar
      ref: v3
      path: packages/isar_generator/
  json_serializable: 6.9.5
  mocktail: 1.0.4
  mocktail_image_network: 1.2.0
  nock: 1.2.3
  state_notifier_test: 0.0.10
  super_lint:
    path: super_lint

flutter_gen:
  output: lib/generated
  line_length: 160

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Cupertino
      fonts:
        - asset: assets/fonts/Cupertino/CupertinoIcons.ttf
    - family: Noto_Sans_JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Thin.ttf
          weight: 100
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Light.ttf
          weight: 300
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Regular.ttf
          weight: 400
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Bold.ttf
          weight: 700
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Noto_Sans_JP/static/NotoSansJP-Black.ttf
          weight: 900
