name: Check Branch Name Convention

on:
  pull_request:
    types: [opened]

jobs:
  check-conventions:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ” Check branch name
        run: |
          echo "ğŸ” Checking branch name: ${{ github.head_ref }}"
          BRANCH="${{ github.head_ref }}"
          if [[ ! "$BRANCH" =~ ^(feat|fix|chore|hotfix)\/[0-9]+(_[0-9]+)?$|^v\.\d+\.\d+\.\d+$ ]]; then
            echo "âŒ Invalid branch name convention: '$BRANCH'"
            echo "âœ… Expected format: 'feat/1234'"
            exit 1
          fi
          echo "âœ… Branch name is valid."